version: "3.3"

services:

  tarantool1:
    image: tarantool/tarantool:latest # 2.8.2 
    # x.x.0 = alpha, x.x.1 = beta, x.x.2+ = stable, latest not always stable
    volumes:
      - ./tarantool-data:/usr/local/share/tarantool
    ports:
      - "3301:3301"
    environment:
      TARANTOOL_USER_NAME: "myusername" 
      TARANTOOL_USER_PASSWORD: "mysecretpassword"
      TT_READAHEAD: '1632000' # 10x   
      TT_VINYL_MEMORY: '2684354560' # 20x
      TT_VINYL_CACHE: '2684354560' # 20x
      TT_NET_MSG_MAX: '76800' # 100x
