#name: Release Example Binary
#
#on:
#  release:
#    types: [created]
#
#jobs:
#  releases-matrix:
#    name: Release Go Binary
#    strategy:
#      matrix:
#        go-version: [1.17.x] #, 1.16.x 
#        # build and publish in parallel: linux/amd64
#        goos: [linux]
#        goarch: [amd64]
#        os: [ubuntu-latest] #, macos-latest, windows-latest]
#    runs-on: ${{ matrix.os }}
#    steps:
#      - name: Install Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: ${{ matrix.go-version }}
#      - uses: actions/checkout@v2
#      - name: Run tests and build binary
#        run: |
#          cd W2/internal/example && go test ./... && go build
#      - name: create release
#        # https://github.com/softprops/action-gh-release
#        uses: softprops/action-gh-release@v1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          files: W2/internal/example/example.exe
