version: "2"
linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - unused
        path: W2/internal/example
      - path: (.+)\.go$
        text: 'composites: .+ struct literal uses unkeyed fields'
      - path: (.+)\.go$
        text: 'SA9003: empty branch'
      - path: (.+)\.go$
        text: 'SA9004: only the first constant in this group has an explicit type'
      - path: (.+)\.go$
        text: '.+Mutator has no field or method .+'
      - path: (.*)\.go$
        text: 'QF1008: could remove embedded field .+'
      - path: (.+)\.go$
        text: "QF1001: could apply De Morgan's law"
      - path: (.+)\.go$
        text: 'QF1010: could convert argument to string'
      - path: (.+)\.go$
        text: 'QF1003: could use tagged switch on .+'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
